# change the followings to match your Github username and repo name
baseurl: "/wip-king-phillips-war" # the name of your github repo
url: "https://BCDigSchol.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Breaking Dawn: King Philip's War"
description: Jekyll site for the King Philip's War Project @ Boston College

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# nav bar settings and links
nav-menu:
  - title: Home
    link: index
  - title: Timeline
    link: timeline
  - title: Present Aims & Future Plans
    link: aims-and-plans
  - title: Bibliography
    link: bibliography

# sets whether a search bar appears on the site header
# NOTE, you will have to increase the site of teh $site-header-height in _sass/theme-settings.scss to to see the search bar
search-bar: false

hide-footer: false # set to true to hide the footer
footer-message: "Breaking Dawn: King Philip's War and the Rise of the Wabanaki, 1675-1715 | CC BY-NC License"
footer-submessage:  By UNCERTAIN, with the Digital Scholarship Group, Boston College
footer-submessage-link: https://ds.bc.edu

# google-analytics: // if you want to use Google analytics, include your ID here

# sets number of items display per page, if using a blog
paginate: 5

include:
  - _pages

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-feed
    - jekyll-paginate
    - jekyll-postcss-v2
